name: Setup HealthOmics Helper StepFunctions
on:
  workflow_dispatch:
    inputs:
      aws_account_id:
        description: 'AWS Account ID'
        required: true
      role_name:
        description: 'Role name to assume'
        default: nigms-omx-helper-role
        required: true
      aws_region:
        description: 'AWS Region'
        default: us-east-1
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  config-cdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ github.event.inputs.aws_account_id }}:role/${{ github.event.inputs.role_name }}
          role-session-name: GitHubActions-HealthOmics-ECR

      - name: Install CDK
        run: npm install -g aws-cdk

      - name: Bootstrap CDK
        run: cdk bootstrap aws://${{ github.event.inputs.aws_account_id }}/${{ github.event.inputs.aws_region }}

      - name: Install dependencies
        run: npm install

      - name: Deploy OMX ECR Helper
        run: cdk deploy aws://${{ github.event.inputs.aws_account_id }}/${{ github.event.inputs.aws_region }} --require-approval never
